name: ist_ciic_env
dependencies:
  - python=3.8
  - numpy
  - notebook
  - nb_conda_kernels
  - matplotlib
  - pip
  - pandas
  - pip:
      - jupyter
      - sympy
      - ipython
      - yapf
      - seaborn
      - psutil
      - tqdm
      - deap
      - ACO-Pants
      - openpyxl
